### ISSUE TITLE
PyG: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyg-lib-feedstock#15]
Raising to track rebuilding for CUDA 12. More details in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 )

Depends on PyTorch CUDA 12 support ( https://github.com/conda-forge/pytorch-cpu-feedstock/issues/163 )

**Comment by hadim** [comment]
I am assuming the migration bot will open a PR right? So not much to do for us here?

**Comment by jakirkham** [comment]
It looks like we need `triton` built for CUDA 12, which should be addressed with PR: https://github.com/conda-forge/triton-feedstock/issues/15

https://github.com/conda-forge/pyg-lib-feedstock/blob/3ea86c8b67db8e7b1c066c1d48146c00ee857dc2/recipe/meta.yaml#L44
