### ISSUE TITLE
Build against multiple pytorch versions

### ISSUE THREAD

**Issue by hadim** [conda-forge/pyg-lib-feedstock#2]
### Comment:

@hmaarrfk this package is built against pytorch but all the package seems to be built against pytorch 1.12 only.

Pytorch 1.11 is still widely used. Any idea why it is not included here? Should I add it manually in the matrix build in a `conda_build_config.yaml` file?

I guess same question for 1.13 (but for this I think a migration is already ongoing).

**Comment by hadim** [comment]
In short: 

```bash
# it fails
micromamba create -n test_pyg_cpu_111 "python=3.10" "pytorch=1.11" "pyg-lib=*=*cpu*"

# it works
micromamba create -n test_pyg_cpu_111 "python=3.10" "pytorch=1.12" "pyg-lib=*=*cpu*"
```

**Comment by hadim** [comment]
Currently making an attempt at https://github.com/conda-forge/pyg-lib-feedstock/pull/3

**Comment by hmaarrfk** [comment]
> Pytorch 1.11 is still widely used. 

Maybe.... But honestly, i don't have the time to maintain it. I've made a few attempts to mold the pytorch build to the conda-forge infrastructure, but given the amount of vendoring, and lack of versions for sub libraries this ended before i could get to the pytorch CPU library.

I'm of the opinion that maintaining more than the latest version of pytorch is too much for me.

It isn't hard to fork and use conda forge infrastructure for a small part of your dependencies.

I would:

1. Update the recipe back to version 1.11.
2. Upload the builds you need for your channel.

**Comment by hmaarrfk** [comment]
3. Target your own dependencies toward pytorch 1.11
4. Slowly upgrade your dependneices.

I honestly tried to go through the process for tensorflow 2.9 recently. I gave up and found a way to work with 2.10

**Comment by hadim** [comment]
I removed the builds for cuda 11.0 and 11.1 so only 11.2 is being used at the moment.

We always try to catch up with the latest versions of pytorch or other important deps but we can't predict the release calendar.

In terms of maintenance, I would be the one maintaining that package so I don't think it will add too much on your shoulder.

**Comment by hadim** [comment]
And if a specific dep version is becoming a burden in the future, we will simply drop it (similar to what has been done for CUDA <11.2).

**Comment by hmaarrfk** [comment]
Unfortunately, even if you get everything built. You will be at the mercy of CFEP03 which would require me (or an other core member) to upload the packages you build.

I just think that at the end of all your effort, i will be too slow to upkoad the packages you build to conda forge.

Do make a PR. We can create the sacred branch later.

Ultimately, you can also just buiold your downstream oackages for a few versions of oyttorch you need. You might have to make a few repodata patches to get the metadata updated.

**Comment by hadim** [comment]
That's fine, I closed the PR and so we'll only build for 1.12 for now.

Can you just confirm the migration bot will trigger a PR for 1.13 here?

**Comment by hmaarrfk** [comment]
It won't trigger a rebuild because we kinda broke everything by skipping old cudas. H vetinari has been issuing the 20 odd PRs manually.

You can always ask not to merge it when he creates it.

**Comment by hmaarrfk** [comment]
Your PR looked perfect. What was wrong with it?

**Comment by hadim** [comment]
> Your PR looked perfect. What was wrong with it?

You said to not build for 1.11? Should I re-open it and use for 1.13 you mean?

**Comment by hadim** [comment]
Maybe there was a misunderstanding here. I re-opened the PR and excluded torch 1.11. Let me know whether you think it's fine.
